config/routes.rb
Elmthomas::Application.routes.draw do
  root :to => 'pages#home'

  match '/education', :to => 'pages#education'
  match '/projects',  :to => 'pages#projects'
  match '/running',   :to => 'pages#running'
  match '/contact',   :to => 'pages#contact'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def education
    @title = "Education"
  end

  def projects
    @title = "Projects"
  end

  def snippets
    @title = "Snippets"
  end

  def running
    @title = "Running"
  end

  def contact
    @title = "Contact"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Eric Thomas'"
    if @title.nil?
      base_title
    else
      "#{base_title} #{@title}"
    end
  end

  def link_to_with_active(name, path)
    link_to_unless_current(name, path) do
      link_to(name, path, { :id => 'current' })
    end  
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <%= link_to 'xhtml', 'http://validator.w3.org/check?uri=referer' %>
  <%= link_to 'css',   'http://jigsaw.w3.org/css-validator/check/referer' %>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1>Eric L. M. Thomas</h1>
  <h2>Software Engineer</h2>

  <nav>
    <ul>
      <li><%= link_to_with_active "Home",      root_path      %></li>
      <li><%= link_to_with_active "Education", education_path %></li>
      <li><%= link_to_with_active "Projects",  projects_path  %></li>
      <li><%= link_to_with_active "Running",   running_path   %></li>
      <li><%= link_to_with_active "Contact",   contact_path   %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
</head>
<body>
  <div id="header-wrapper">
    <%= render 'layouts/header' %>
  </div>

  <div class="container">
    <section class="round-bottom">
      <%= yield %>
    </section>
  </div>

</body>
</html>

app/views/pages/contact.html.erb
<p>Click <%= link_to "here", "http://www.google.com/recaptcha/mailhide/d?k=01rmiLIORUajSUe74b2pZIsg==&c=lOLICsUCMK1pqLmYTCFAh8h9Dh3r2nVFYqtqZacoRyE=" %> to reveal my email.</p>

app/views/pages/education.html.erb
<p>My <%= link_to "resume", "/files/education/eric_thomas_resume.pdf" %>,
  (<%= link_to "latex source",
              "http://github.com/et/resume/blob/master/eric_thomas.tex" %>).</p>
<p>I graduated from Rowan University in May of 2009 with a B.S. in
   Computer Science. I have specializations in Software Engineering, Information
   Technology, Programming Languages &amp; Compilers, and Artificial Intelligence.</p>
<p>If you would like a copy of my transcript,
   please <%= link_to "contact me", contact_path %>.</p>

app/views/pages/home.html.erb
<p>
  Welcome to Eric Thomas' website. I am currently employed with
  <%= image_tag "me.jpg", :class => "right" %>
  <%= link_to "Aspera", "http://www.asperasoft.com" %>
  developing web applications.</p>
<p>I have been learning as much as I can about the CS field since my
  early years in high school. Since graduating from my
  <%= link_to "alma mater", "http://www.rowan.edu" %> and embarking
  on my journey as a full time programmer, I've found that my style has
  changed greatly.<br />
  I feel that a programmer's tools and traits reveal a lot
  about a person, so without further ado:</p>
<ul>
  <li>Editor - vim</li>
  <li>Version control - git</li>
  <li># of spaces for indenting - 2</li>
  <li>Window manager - Gnome 3</li>
  <li>Language - Ruby/C++/bash</li>
</ul>

<p>Outside of the CS field, I enjoy <%= link_to "running", running_path %>,
   zombie movies, live music, diners, road trips, board games, microbrewed
   beers, and trying new things.</p>

app/views/pages/projects.html.erb
<p>Here are some of the projects I've done over the years. Not all of the
   source code is available since it was done for work. While my current
   job keeps me busy, I do a little bit of
   <%= link_to "casual coding", "http://github.com/et" %> on the side.
</p>

<h2>drum-tabber</h2>
<p>drum-tabber was my senior project. In short, the application creates
   <%= image_tag "drum_tabber.png", :class => "left" %>
   drum tablature (ASCII music notation) for drummers who play with electronic
   drum kits. It does this by receiving MIDI signals and then decrypting them
   to the correct tablature. The application facilitates drummers who want to
   write their music out (or other drummers' music) in a more efficient
   manner.<br />
   Alternatively, drum-tabber can be used for beginner drummers that have
   difficulty keeping a steady tempo when playing<br />
   <%= link_to "drum-tabber Home Page", "http://code.google.com/p/drum-tabber/" %>
</p>

<h2>arimaai</h2>
<p>arimaaai is a computer bot that my friend and I are developing to play
   <%= link_to "Arimaa", "http://arimaa.com/arimaa/" %>, a board game that has
   been proven to be a more difficult challenge for AI than chess. Arimaa is
   especially hard becaue of the branching factor involved. With chess, you can
   only move one piece in a given turn. In Arimaa, you can move as many as four
   pieces in a single turn which makes it extremely difficult for computers to
   look ahead. Rather than trying to determine every single possible move, our
   bot focuses on certain sections of the board and tries to evalute moves only
   in certain areas.<br />
   <%= link_to "View our repository", "http://github.com/ecks/arimaai/tree/master" %>
</p>

<h2>FlightGUI</h2>
<p>FlightGUI is an application that displays a graphical display of two previous
   <%= image_tag "flightgui_small.png", :class => "left" %>
   flights that once had an encounter or a conflict. The program gives an
   animation of the two flights and the data that is pertinent. This application
   is used by analysts to adjust their trajectory prediction algorithms to avoid
   potential encounters or conflicts in the future. I worked with a group of
   students from Rowan University and Fairfield University to develop this
   application during spring of 2008.<br />
   <%= link_to "View screenshot", "/images/flightgui_big.png" %>
</p>

<h2>WebGPS</h2>
<p>WebGPS is essentially a way to interact with an information hierarchy in real
   <%= image_tag "webgps_small.png", :class => "left" %>
   time.  It uses the Web as a practical application. If you examine the
   <%= link_to "screenshot", "/images/webgps_big.png" %>, you'll see it has
   mapped all the pages that are linked on Rowan University's Web page. The
   large circle that is greyed, maps to the College of Business link. All the
   circles inside there are all the links inside the College of Business'
   sub-site. The other small greyed circles are also College of Business links
   contained in other sub sites of Rowan's site.  A study showed that users who
   used the program were able to locate Web pages of interest faster.<br />
   I worked on a redesign of this application with a graduate student during the
   fall of 2008 to make it faster and useable in any browser (the first design
   had a built in browser). The program is still in active development.<br />
   <%= link_to "View screenshot", "/images/webgps_big.png" %>
</p>

<h2>IDEA</h2>
<p>The Institute for the Development of the Arts is a non-profit organization
   <%= image_tag "idea_small.png", :class => "left" %>
   that provides education in the arts to the youth of Camden City, New Jersey.
   I worked at the organization during the summer of 2007. My role was teach a
   small group of students about web development and design. I also created the
   organization's website which utilized a small amount of PHP and AJAX and is
   XHTML 1.0 valid.<br />
   <%= link_to "View screenshot", "/images/idea_big.png" %>
</p>

app/views/pages/running.html.erb
<p>Running is something that I have a strong passion for in life.
   <%= image_tag("me_running.jpg", :class=> "left") %>
   I find that it becomes difficult going a day without getting the
   daily run in since running is what keeps me focused and driven.
   Running has kept me in great shape, introduced me to many new people,
   and given me a great outlook on life.
   I've been involved in competitive distance running for the past ten
   years of my life and plan on continuing for many years to come.</p>

<p>My personal records are:<br />
   800m: 2:05<br />
   1500m: 4:16<br />
   1600m: 4:34<br />
   5000m: 16:04<br />
   8000m: 26:28<br />
   10000m: 34:10<br />
   Marathon: 2:52:11</p>